# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zn1q3FFCJsDUQNxNLphCynm5aJk-rihM
"""

ans = int(id_last_digit) % 2 == 1