# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zn1q3FFCJsDUQNxNLphCynm5aJk-rihM
"""

id_last_digit = input("請輸入您身分證字號的尾數")