# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rW9hGBfz2hDJSS5Af19a3DecBO8Eq3YG
"""

print = 5566

movie_title = "Avengers: Endgame"
print(movie_title)

print = 5566
del print

movie_title = "Avengers: Endgame"
print(movie_title)

help(abs)

help(all)

my_object = 5566
print(my_object)

my_str = '5566'
print(my_str)

print(type(my_object))
print(type(my_str))

movie_title = "Avengers: Endgame"
movie_length = 181
movie_rating = 8.4

print(movie_title)
print(movie_length)
print(movie_rating)

print(type(movie_title))
print(type(movie_length))
print(type(movie_rating))