# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ViQCXnN_yYBJceAXQ3EzQrhSl2ePR2Zr
"""

def F2C(F):
    C=(F-32) * 5 /9
    return C

def C2F(C):
    F= C * (9/5) + 32
    return F

degree = int(input("Please input degree:"))
conversion=int(input("1.Celsius-> Fahrenheit. 2.Fahrenheit->Celsius."))
if conversion == 1:
    F=C2F(degree)
    print ("%d Celsius = %d Fahrenheit" % (degree,F))
elif conversion == 2:
    C=F2C(degree)
    print ("%d Fahrenheit = %d Celsius" % (degree,C))

oneal_height = 216
oneal_weight = 147
oneal_bmi = oneal_weight / (oneal_height/100)**2
print(oneal_bmi)

ross_said = 'Let\'s put aside the fact that you "accidentally" pick up my grandmother\'s ring.'
print(ross_said)

city = input("請輸入你在的城市:")
weather = input("請輸入目前的天氣:")

print("我在{}，天氣{}".format(city, weather))

print(type(True))
print(type(False))

movie_rating = 7.7
print(movie_rating > 8)

