# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fC2JkDKpRonmPu0q3jNaSJeELvfulu4o
"""

get_bmi(216, 147)