# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fC2JkDKpRonmPu0q3jNaSJeELvfulu4o
"""

from statistics import stdev

stdev(range(1, 101)) # [1, 2, 3, ..., 100]