# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fC2JkDKpRonmPu0q3jNaSJeELvfulu4o
"""

n_vowels = 0 
for i in 'azcbobobegghak':
    if i in ['a', 'e', 'i', 'o', 'u']:
        #print(i)
        n_vowels += 1
print(n_vowels)