# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eMaA4h2QpCg8DjUYrfLpA0wq0mz88H73
"""

avengers = ["The Avengers", "Avengers: Age of Ultron", "Avengers: Infinity War", "Avengers: Endgame"]
for idx, movie in enumerate(avengers):
    print("第 {} 部上映的復仇者聯盟電影:{}".format(idx+1, movie))