# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P7F3KLWf3zmqjPymRAm_6TmOfbUYsdsV
"""

primes_list = [2, 3, 5, 7, 11]
primes_list[-1] = 13 # update
print(primes_list)

primes_list.insert(-1, 11) # increase length
print(primes_list)

primes_list.pop()
print(primes_list)