# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P7F3KLWf3zmqjPymRAm_6TmOfbUYsdsV
"""

primes = (2, 3, 5, 7, 11)
print(type(primes))