# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P7F3KLWf3zmqjPymRAm_6TmOfbUYsdsV
"""

my_city, my_country = where_are_you_from("Taipei", "Taiwan")
print(my_city)
print(my_country)