# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P7F3KLWf3zmqjPymRAm_6TmOfbUYsdsV
"""

x = 0.25
print(type(x))
print(x.as_integer_ratio())
print(type(x.as_integer_ratio()))

numerator, denominator = x.as_integer_ratio()
print(numerator)
print(denominator)