# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13WezOqXqfnZKqGar0azIYO3zfkvgOdcc
"""

actor_0 = cast_list_a[0].get('alt').strip()
cast_list.append(actor_0)
print(cast_list)