# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13WezOqXqfnZKqGar0azIYO3zfkvgOdcc
"""

!pip install -U beautifulsoup4