# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13WezOqXqfnZKqGar0azIYO3zfkvgOdcc
"""

cast_list_a = soup.select("#titleCast .loadlate")
print(len(cast_list_a))