# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13WezOqXqfnZKqGar0azIYO3zfkvgOdcc
"""

import requests
from bs4 import BeautifulSoup

response = requests.get('https://www.imdb.com/title/tt4154796/')
soup = BeautifulSoup(response.text)