# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13WezOqXqfnZKqGar0azIYO3zfkvgOdcc
"""

actor_1 = cast_list_a[1].get('alt').strip()
cast_list.append(actor_1)
print(cast_list)